name: dash_counterfactuals
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - dash
  - dash-table
  - r-base
  - r-essentials
  - rpy2
  - r-bnclassify
  - r-e1071
  - pip
  - pip:
      - dash-bootstrap-components  # Installed from PyPI
